### ISSUE TITLE
[Question] Ignore if key is pressed

### ISSUE THREAD

**Issue by Chirunos** [aggro80/linux-macro-recorder#1]
Is there a way I can modify the program so that it doesn't abort the macro if a key (except for F9, of course) is pressed?

**Comment by aggro80** [comment]
I assume you mean in the reply mode. Again, this project was just a quick hack and I have no intention of maintaining this, so be aware of potential problems. But I think you need to do something like this. (didn't try to compile, but you can probably figure out the rest)

You need to modify this part:
```
			printf("Aborted by keyboard action\n");
			break;
```

Replace it with something like this   :
```
input_event ev;

			if( read(pfds[0].fd, &ev, sizeof(struct input_event)) != sizeof(struct input_event))
				{
					printf("Error: \n");
					break;
				}

				if( ev.code == KEY_F9))
				{
                                        printf("Aborted by keyboard F9\n");
					break;
				}
```

**Comment by Chirunos** [comment]
Thank you, made a fork adapting the change!
